controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
easyadmin:
    resource: .
    type: easyadmin.routes
    prefix: /admin
api_login_check:
    path: /api/login_check