nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: My documentation
            version: 1.0.0
        tags:
            - name: 'User'
              description: 'Endpoints related to user information'
            - name: 'Quiz'
              description: 'Endpoints related to quizzes'
            - name: 'Favourites'
              description: 'Favourite quizzes for user'
            - name: 'Security'
              description: 'Endpoints related to authorization'
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        areas: # to filter documented areas
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc$